# config/packages/nucleos_user.yaml
nucleos_user:
    db_driver: orm # other valid values is 'mongodb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:   "infoamine994@gmail.com"
    loggedin:
        route: 'home' #